/********************************************************************************
** Form generated from reading UI file 'mainwindow.ui'
**
** Created by: Qt User Interface Compiler version 4.8.7
**
** WARNING! All changes made in this file will be lost when recompiling UI file!
********************************************************************************/

#ifndef UI_MAINWINDOW_H
#define UI_MAINWINDOW_H

#include <QtCore/QVariant>
#include <QtGui/QAction>
#include <QtGui/QApplication>
#include <QtGui/QButtonGroup>
#include <QtGui/QCheckBox>
#include <QtGui/QFrame>
#include <QtGui/QGroupBox>
#include <QtGui/QHeaderView>
#include <QtGui/QLabel>
#include <QtGui/QMainWindow>
#include <QtGui/QMenuBar>
#include <QtGui/QProgressBar>
#include <QtGui/QPushButton>
#include <QtGui/QSlider>
#include <QtGui/QWidget>

QT_BEGIN_NAMESPACE

class Ui_mainWindow
{
public:
    QWidget *centralWidget;
    QFrame *frame;
    QPushButton *robot1;
    QPushButton *robot3;
    QPushButton *robot2;
    QFrame *line;
    QFrame *line_2;
    QFrame *line_3;
    QFrame *line_5;
    QFrame *line_6;
    QFrame *line_7;
    QFrame *line_8;
    QFrame *line_9;
    QFrame *line_10;
    QFrame *line_11;
    QFrame *line_12;
    QFrame *line_13;
    QFrame *line_14;
    QFrame *line_15;
    QFrame *line_4;
    QFrame *line_16;
    QFrame *line_17;
    QFrame *line_18;
    QFrame *line_19;
    QFrame *line_20;
    QFrame *line_21;
    QFrame *line_22;
    QFrame *line_23;
    QFrame *line_24;
    QFrame *line_25;
    QFrame *line_26;
    QFrame *line_27;
    QFrame *line_28;
    QFrame *line_29;
    QFrame *line_30;
    QFrame *line_31;
    QFrame *line_32;
    QFrame *line_33;
    QGroupBox *groupBox;
    QLabel *rob3_y;
    QLabel *rob3_x;
    QLabel *rob2_y;
    QLabel *label_2;
    QLabel *label;
    QLabel *label_4;
    QLabel *label_5;
    QLabel *label_3;
    QLabel *rob1_y;
    QLabel *rob1_x;
    QLabel *rob2_x;
    QGroupBox *groupBox_2;
    QSlider *horizontalSlider;
    QSlider *horizontalSlider_2;
    QSlider *horizontalSlider_3;
    QLabel *label_6;
    QLabel *label_7;
    QLabel *label_8;
    QSlider *horizontalSlider_4;
    QCheckBox *checkBox;
    QCheckBox *checkBox_2;
    QCheckBox *checkBox_3;
    QLabel *label_11;
    QCheckBox *checkBox_4;
    QLabel *label_12;
    QLabel *label_13;
    QLabel *label_14;
    QLabel *label_15;
    QGroupBox *groupBox_3;
    QProgressBar *progressBar;
    QLabel *label_9;
    QLabel *itens_l;
    QLabel *max_l;
    QLabel *label_10;
    QPushButton *pushButton;
    QPushButton *pushButton_2;
    QPushButton *pushButton_3;
    QMenuBar *menuBar;

    void setupUi(QMainWindow *mainWindow)
    {
        if (mainWindow->objectName().isEmpty())
            mainWindow->setObjectName(QString::fromUtf8("mainWindow"));
        mainWindow->resize(740, 430);
        mainWindow->setMinimumSize(QSize(740, 430));
        mainWindow->setMaximumSize(QSize(740, 500));
        mainWindow->setDocumentMode(false);
        mainWindow->setTabShape(QTabWidget::Rounded);
        mainWindow->setUnifiedTitleAndToolBarOnMac(false);
        centralWidget = new QWidget(mainWindow);
        centralWidget->setObjectName(QString::fromUtf8("centralWidget"));
        frame = new QFrame(centralWidget);
        frame->setObjectName(QString::fromUtf8("frame"));
        frame->setGeometry(QRect(10, 10, 400, 300));
        frame->setFrameShape(QFrame::Box);
        frame->setFrameShadow(QFrame::Plain);
        frame->setLineWidth(2);
        robot1 = new QPushButton(frame);
        robot1->setObjectName(QString::fromUtf8("robot1"));
        robot1->setGeometry(QRect(0, 0, 20, 20));
        robot3 = new QPushButton(frame);
        robot3->setObjectName(QString::fromUtf8("robot3"));
        robot3->setGeometry(QRect(40, 0, 20, 20));
        robot2 = new QPushButton(frame);
        robot2->setObjectName(QString::fromUtf8("robot2"));
        robot2->setGeometry(QRect(20, 0, 20, 20));
        line = new QFrame(frame);
        line->setObjectName(QString::fromUtf8("line"));
        line->setEnabled(false);
        line->setGeometry(QRect(0, 20, 401, 1));
        line->setMaximumSize(QSize(16777215, 1));
        line->setFrameShadow(QFrame::Plain);
        line->setFrameShape(QFrame::HLine);
        line_2 = new QFrame(frame);
        line_2->setObjectName(QString::fromUtf8("line_2"));
        line_2->setEnabled(false);
        line_2->setGeometry(QRect(0, 40, 401, 1));
        line_2->setMaximumSize(QSize(16777215, 1));
        line_2->setFrameShadow(QFrame::Plain);
        line_2->setFrameShape(QFrame::HLine);
        line_3 = new QFrame(frame);
        line_3->setObjectName(QString::fromUtf8("line_3"));
        line_3->setEnabled(false);
        line_3->setGeometry(QRect(0, 60, 401, 1));
        line_3->setMaximumSize(QSize(16777215, 1));
        line_3->setFrameShadow(QFrame::Plain);
        line_3->setFrameShape(QFrame::HLine);
        line_5 = new QFrame(frame);
        line_5->setObjectName(QString::fromUtf8("line_5"));
        line_5->setEnabled(false);
        line_5->setGeometry(QRect(0, 100, 401, 1));
        line_5->setMaximumSize(QSize(16777215, 1));
        line_5->setFrameShadow(QFrame::Plain);
        line_5->setFrameShape(QFrame::HLine);
        line_6 = new QFrame(frame);
        line_6->setObjectName(QString::fromUtf8("line_6"));
        line_6->setEnabled(false);
        line_6->setGeometry(QRect(0, 80, 401, 1));
        line_6->setMaximumSize(QSize(16777215, 1));
        line_6->setFrameShadow(QFrame::Plain);
        line_6->setFrameShape(QFrame::HLine);
        line_7 = new QFrame(frame);
        line_7->setObjectName(QString::fromUtf8("line_7"));
        line_7->setEnabled(false);
        line_7->setGeometry(QRect(0, 120, 401, 1));
        line_7->setMaximumSize(QSize(16777215, 1));
        line_7->setFrameShadow(QFrame::Plain);
        line_7->setFrameShape(QFrame::HLine);
        line_8 = new QFrame(frame);
        line_8->setObjectName(QString::fromUtf8("line_8"));
        line_8->setEnabled(false);
        line_8->setGeometry(QRect(0, 140, 401, 1));
        line_8->setMaximumSize(QSize(16777215, 1));
        line_8->setFrameShadow(QFrame::Plain);
        line_8->setFrameShape(QFrame::HLine);
        line_9 = new QFrame(frame);
        line_9->setObjectName(QString::fromUtf8("line_9"));
        line_9->setEnabled(false);
        line_9->setGeometry(QRect(0, 160, 401, 1));
        line_9->setMaximumSize(QSize(16777215, 1));
        line_9->setFrameShadow(QFrame::Plain);
        line_9->setFrameShape(QFrame::HLine);
        line_10 = new QFrame(frame);
        line_10->setObjectName(QString::fromUtf8("line_10"));
        line_10->setEnabled(false);
        line_10->setGeometry(QRect(0, 180, 401, 1));
        line_10->setMaximumSize(QSize(16777215, 1));
        line_10->setFrameShadow(QFrame::Plain);
        line_10->setFrameShape(QFrame::HLine);
        line_11 = new QFrame(frame);
        line_11->setObjectName(QString::fromUtf8("line_11"));
        line_11->setEnabled(false);
        line_11->setGeometry(QRect(0, 200, 401, 1));
        line_11->setMaximumSize(QSize(16777215, 1));
        line_11->setFrameShadow(QFrame::Plain);
        line_11->setFrameShape(QFrame::HLine);
        line_12 = new QFrame(frame);
        line_12->setObjectName(QString::fromUtf8("line_12"));
        line_12->setEnabled(false);
        line_12->setGeometry(QRect(0, 220, 401, 1));
        line_12->setMaximumSize(QSize(16777215, 1));
        line_12->setFrameShadow(QFrame::Plain);
        line_12->setFrameShape(QFrame::HLine);
        line_13 = new QFrame(frame);
        line_13->setObjectName(QString::fromUtf8("line_13"));
        line_13->setEnabled(false);
        line_13->setGeometry(QRect(0, 240, 401, 1));
        line_13->setMaximumSize(QSize(16777215, 1));
        line_13->setFrameShadow(QFrame::Plain);
        line_13->setFrameShape(QFrame::HLine);
        line_14 = new QFrame(frame);
        line_14->setObjectName(QString::fromUtf8("line_14"));
        line_14->setEnabled(false);
        line_14->setGeometry(QRect(0, 260, 401, 1));
        line_14->setMaximumSize(QSize(16777215, 1));
        line_14->setFrameShadow(QFrame::Plain);
        line_14->setFrameShape(QFrame::HLine);
        line_15 = new QFrame(frame);
        line_15->setObjectName(QString::fromUtf8("line_15"));
        line_15->setEnabled(false);
        line_15->setGeometry(QRect(0, 280, 401, 1));
        line_15->setMaximumSize(QSize(16777215, 1));
        line_15->setFrameShadow(QFrame::Plain);
        line_15->setFrameShape(QFrame::HLine);
        line_4 = new QFrame(frame);
        line_4->setObjectName(QString::fromUtf8("line_4"));
        line_4->setEnabled(false);
        line_4->setGeometry(QRect(20, 0, 1, 301));
        line_4->setFrameShadow(QFrame::Plain);
        line_4->setFrameShape(QFrame::VLine);
        line_16 = new QFrame(frame);
        line_16->setObjectName(QString::fromUtf8("line_16"));
        line_16->setEnabled(false);
        line_16->setGeometry(QRect(40, 0, 1, 301));
        line_16->setFrameShadow(QFrame::Plain);
        line_16->setFrameShape(QFrame::VLine);
        line_17 = new QFrame(frame);
        line_17->setObjectName(QString::fromUtf8("line_17"));
        line_17->setEnabled(false);
        line_17->setGeometry(QRect(60, 0, 1, 301));
        line_17->setFrameShadow(QFrame::Plain);
        line_17->setFrameShape(QFrame::VLine);
        line_18 = new QFrame(frame);
        line_18->setObjectName(QString::fromUtf8("line_18"));
        line_18->setEnabled(false);
        line_18->setGeometry(QRect(80, 0, 1, 301));
        line_18->setFrameShadow(QFrame::Plain);
        line_18->setFrameShape(QFrame::VLine);
        line_19 = new QFrame(frame);
        line_19->setObjectName(QString::fromUtf8("line_19"));
        line_19->setEnabled(false);
        line_19->setGeometry(QRect(100, 0, 1, 301));
        line_19->setFrameShadow(QFrame::Plain);
        line_19->setFrameShape(QFrame::VLine);
        line_20 = new QFrame(frame);
        line_20->setObjectName(QString::fromUtf8("line_20"));
        line_20->setEnabled(false);
        line_20->setGeometry(QRect(120, 0, 1, 301));
        line_20->setFrameShadow(QFrame::Plain);
        line_20->setFrameShape(QFrame::VLine);
        line_21 = new QFrame(frame);
        line_21->setObjectName(QString::fromUtf8("line_21"));
        line_21->setEnabled(false);
        line_21->setGeometry(QRect(140, 0, 1, 301));
        line_21->setFrameShadow(QFrame::Plain);
        line_21->setFrameShape(QFrame::VLine);
        line_22 = new QFrame(frame);
        line_22->setObjectName(QString::fromUtf8("line_22"));
        line_22->setEnabled(false);
        line_22->setGeometry(QRect(160, 0, 1, 301));
        line_22->setFrameShadow(QFrame::Plain);
        line_22->setFrameShape(QFrame::VLine);
        line_23 = new QFrame(frame);
        line_23->setObjectName(QString::fromUtf8("line_23"));
        line_23->setEnabled(false);
        line_23->setGeometry(QRect(180, 0, 1, 301));
        line_23->setFrameShadow(QFrame::Plain);
        line_23->setFrameShape(QFrame::VLine);
        line_24 = new QFrame(frame);
        line_24->setObjectName(QString::fromUtf8("line_24"));
        line_24->setEnabled(false);
        line_24->setGeometry(QRect(200, 0, 1, 301));
        line_24->setFrameShadow(QFrame::Plain);
        line_24->setFrameShape(QFrame::VLine);
        line_25 = new QFrame(frame);
        line_25->setObjectName(QString::fromUtf8("line_25"));
        line_25->setEnabled(false);
        line_25->setGeometry(QRect(220, 0, 1, 301));
        line_25->setFrameShadow(QFrame::Plain);
        line_25->setFrameShape(QFrame::VLine);
        line_26 = new QFrame(frame);
        line_26->setObjectName(QString::fromUtf8("line_26"));
        line_26->setEnabled(false);
        line_26->setGeometry(QRect(240, 0, 1, 301));
        line_26->setFrameShadow(QFrame::Plain);
        line_26->setFrameShape(QFrame::VLine);
        line_27 = new QFrame(frame);
        line_27->setObjectName(QString::fromUtf8("line_27"));
        line_27->setEnabled(false);
        line_27->setGeometry(QRect(260, 0, 1, 301));
        line_27->setFrameShadow(QFrame::Plain);
        line_27->setFrameShape(QFrame::VLine);
        line_28 = new QFrame(frame);
        line_28->setObjectName(QString::fromUtf8("line_28"));
        line_28->setEnabled(false);
        line_28->setGeometry(QRect(280, 0, 1, 301));
        line_28->setFrameShadow(QFrame::Plain);
        line_28->setFrameShape(QFrame::VLine);
        line_29 = new QFrame(frame);
        line_29->setObjectName(QString::fromUtf8("line_29"));
        line_29->setEnabled(false);
        line_29->setGeometry(QRect(300, 0, 1, 301));
        line_29->setFrameShadow(QFrame::Plain);
        line_29->setFrameShape(QFrame::VLine);
        line_30 = new QFrame(frame);
        line_30->setObjectName(QString::fromUtf8("line_30"));
        line_30->setEnabled(false);
        line_30->setGeometry(QRect(320, 0, 1, 301));
        line_30->setFrameShadow(QFrame::Plain);
        line_30->setFrameShape(QFrame::VLine);
        line_31 = new QFrame(frame);
        line_31->setObjectName(QString::fromUtf8("line_31"));
        line_31->setEnabled(false);
        line_31->setGeometry(QRect(340, 0, 1, 301));
        line_31->setFrameShadow(QFrame::Plain);
        line_31->setFrameShape(QFrame::VLine);
        line_32 = new QFrame(frame);
        line_32->setObjectName(QString::fromUtf8("line_32"));
        line_32->setEnabled(false);
        line_32->setGeometry(QRect(360, 0, 1, 301));
        line_32->setFrameShadow(QFrame::Plain);
        line_32->setFrameShape(QFrame::VLine);
        line_33 = new QFrame(frame);
        line_33->setObjectName(QString::fromUtf8("line_33"));
        line_33->setEnabled(false);
        line_33->setGeometry(QRect(380, 0, 1, 301));
        line_33->setFrameShadow(QFrame::Plain);
        line_33->setFrameShape(QFrame::VLine);
        line->raise();
        line_2->raise();
        line_3->raise();
        line_5->raise();
        line_6->raise();
        line_7->raise();
        line_8->raise();
        line_9->raise();
        line_10->raise();
        line_11->raise();
        line_12->raise();
        line_13->raise();
        line_14->raise();
        line_15->raise();
        line_4->raise();
        line_16->raise();
        line_17->raise();
        line_18->raise();
        line_19->raise();
        line_20->raise();
        line_21->raise();
        line_22->raise();
        line_23->raise();
        line_24->raise();
        line_25->raise();
        line_26->raise();
        line_27->raise();
        line_28->raise();
        line_29->raise();
        line_30->raise();
        line_31->raise();
        line_32->raise();
        line_33->raise();
        robot1->raise();
        robot2->raise();
        robot3->raise();
        groupBox = new QGroupBox(centralWidget);
        groupBox->setObjectName(QString::fromUtf8("groupBox"));
        groupBox->setGeometry(QRect(420, 10, 301, 121));
        groupBox->setFlat(false);
        groupBox->setCheckable(false);
        rob3_y = new QLabel(groupBox);
        rob3_y->setObjectName(QString::fromUtf8("rob3_y"));
        rob3_y->setGeometry(QRect(220, 90, 31, 17));
        rob3_y->setAlignment(Qt::AlignCenter);
        rob3_x = new QLabel(groupBox);
        rob3_x->setObjectName(QString::fromUtf8("rob3_x"));
        rob3_x->setGeometry(QRect(150, 90, 31, 17));
        rob3_x->setAlignment(Qt::AlignCenter);
        rob2_y = new QLabel(groupBox);
        rob2_y->setObjectName(QString::fromUtf8("rob2_y"));
        rob2_y->setGeometry(QRect(220, 60, 31, 17));
        rob2_y->setAlignment(Qt::AlignCenter);
        label_2 = new QLabel(groupBox);
        label_2->setObjectName(QString::fromUtf8("label_2"));
        label_2->setGeometry(QRect(50, 60, 61, 17));
        label = new QLabel(groupBox);
        label->setObjectName(QString::fromUtf8("label"));
        label->setGeometry(QRect(50, 30, 61, 17));
        label_4 = new QLabel(groupBox);
        label_4->setObjectName(QString::fromUtf8("label_4"));
        label_4->setGeometry(QRect(150, 10, 31, 17));
        label_4->setAlignment(Qt::AlignCenter);
        label_5 = new QLabel(groupBox);
        label_5->setObjectName(QString::fromUtf8("label_5"));
        label_5->setGeometry(QRect(220, 10, 31, 17));
        label_5->setAlignment(Qt::AlignCenter);
        label_3 = new QLabel(groupBox);
        label_3->setObjectName(QString::fromUtf8("label_3"));
        label_3->setGeometry(QRect(50, 90, 61, 17));
        rob1_y = new QLabel(groupBox);
        rob1_y->setObjectName(QString::fromUtf8("rob1_y"));
        rob1_y->setGeometry(QRect(220, 30, 31, 17));
        rob1_y->setAlignment(Qt::AlignCenter);
        rob1_x = new QLabel(groupBox);
        rob1_x->setObjectName(QString::fromUtf8("rob1_x"));
        rob1_x->setGeometry(QRect(150, 30, 31, 17));
        rob1_x->setAlignment(Qt::AlignCenter);
        rob2_x = new QLabel(groupBox);
        rob2_x->setObjectName(QString::fromUtf8("rob2_x"));
        rob2_x->setGeometry(QRect(150, 60, 31, 17));
        rob2_x->setAlignment(Qt::AlignCenter);
        groupBox_2 = new QGroupBox(centralWidget);
        groupBox_2->setObjectName(QString::fromUtf8("groupBox_2"));
        groupBox_2->setGeometry(QRect(420, 140, 301, 171));
        horizontalSlider = new QSlider(groupBox_2);
        horizontalSlider->setObjectName(QString::fromUtf8("horizontalSlider"));
        horizontalSlider->setGeometry(QRect(20, 30, 211, 16));
        horizontalSlider->setMinimum(100);
        horizontalSlider->setMaximum(4000);
        horizontalSlider->setValue(4000);
        horizontalSlider->setOrientation(Qt::Horizontal);
        horizontalSlider->setInvertedAppearance(false);
        horizontalSlider->setTickPosition(QSlider::TicksBelow);
        horizontalSlider->setTickInterval(200);
        horizontalSlider_2 = new QSlider(groupBox_2);
        horizontalSlider_2->setObjectName(QString::fromUtf8("horizontalSlider_2"));
        horizontalSlider_2->setGeometry(QRect(20, 70, 211, 16));
        horizontalSlider_2->setMinimum(100);
        horizontalSlider_2->setMaximum(4000);
        horizontalSlider_2->setValue(4000);
        horizontalSlider_2->setOrientation(Qt::Horizontal);
        horizontalSlider_2->setTickPosition(QSlider::TicksBelow);
        horizontalSlider_2->setTickInterval(200);
        horizontalSlider_3 = new QSlider(groupBox_2);
        horizontalSlider_3->setObjectName(QString::fromUtf8("horizontalSlider_3"));
        horizontalSlider_3->setGeometry(QRect(20, 110, 211, 16));
        horizontalSlider_3->setMinimum(100);
        horizontalSlider_3->setMaximum(4000);
        horizontalSlider_3->setValue(4000);
        horizontalSlider_3->setOrientation(Qt::Horizontal);
        horizontalSlider_3->setTickPosition(QSlider::TicksBelow);
        horizontalSlider_3->setTickInterval(200);
        label_6 = new QLabel(groupBox_2);
        label_6->setObjectName(QString::fromUtf8("label_6"));
        label_6->setGeometry(QRect(240, 20, 41, 31));
        label_7 = new QLabel(groupBox_2);
        label_7->setObjectName(QString::fromUtf8("label_7"));
        label_7->setGeometry(QRect(240, 60, 41, 31));
        label_8 = new QLabel(groupBox_2);
        label_8->setObjectName(QString::fromUtf8("label_8"));
        label_8->setGeometry(QRect(240, 100, 41, 31));
        horizontalSlider_4 = new QSlider(groupBox_2);
        horizontalSlider_4->setObjectName(QString::fromUtf8("horizontalSlider_4"));
        horizontalSlider_4->setGeometry(QRect(20, 150, 211, 16));
        horizontalSlider_4->setMinimum(10);
        horizontalSlider_4->setMaximum(1000);
        horizontalSlider_4->setSingleStep(5);
        horizontalSlider_4->setPageStep(10);
        horizontalSlider_4->setValue(100);
        horizontalSlider_4->setOrientation(Qt::Horizontal);
        horizontalSlider_4->setTickPosition(QSlider::TicksBelow);
        horizontalSlider_4->setTickInterval(20);
        checkBox = new QCheckBox(groupBox_2);
        checkBox->setObjectName(QString::fromUtf8("checkBox"));
        checkBox->setGeometry(QRect(280, 20, 21, 31));
        checkBox->setChecked(true);
        checkBox_2 = new QCheckBox(groupBox_2);
        checkBox_2->setObjectName(QString::fromUtf8("checkBox_2"));
        checkBox_2->setGeometry(QRect(280, 60, 21, 31));
        checkBox_2->setChecked(true);
        checkBox_3 = new QCheckBox(groupBox_2);
        checkBox_3->setObjectName(QString::fromUtf8("checkBox_3"));
        checkBox_3->setGeometry(QRect(280, 100, 21, 31));
        checkBox_3->setChecked(true);
        label_11 = new QLabel(groupBox_2);
        label_11->setObjectName(QString::fromUtf8("label_11"));
        label_11->setGeometry(QRect(240, 140, 41, 31));
        checkBox_4 = new QCheckBox(groupBox_2);
        checkBox_4->setObjectName(QString::fromUtf8("checkBox_4"));
        checkBox_4->setGeometry(QRect(280, 140, 21, 31));
        checkBox_4->setChecked(true);
        label_12 = new QLabel(groupBox_2);
        label_12->setObjectName(QString::fromUtf8("label_12"));
        label_12->setGeometry(QRect(0, 20, 16, 31));
        label_13 = new QLabel(groupBox_2);
        label_13->setObjectName(QString::fromUtf8("label_13"));
        label_13->setGeometry(QRect(0, 60, 16, 31));
        label_14 = new QLabel(groupBox_2);
        label_14->setObjectName(QString::fromUtf8("label_14"));
        label_14->setGeometry(QRect(0, 100, 16, 31));
        label_15 = new QLabel(groupBox_2);
        label_15->setObjectName(QString::fromUtf8("label_15"));
        label_15->setGeometry(QRect(0, 140, 16, 31));
        groupBox_3 = new QGroupBox(centralWidget);
        groupBox_3->setObjectName(QString::fromUtf8("groupBox_3"));
        groupBox_3->setGeometry(QRect(10, 320, 701, 81));
        progressBar = new QProgressBar(groupBox_3);
        progressBar->setObjectName(QString::fromUtf8("progressBar"));
        progressBar->setGeometry(QRect(10, 30, 681, 23));
        progressBar->setValue(0);
        label_9 = new QLabel(groupBox_3);
        label_9->setObjectName(QString::fromUtf8("label_9"));
        label_9->setGeometry(QRect(10, 50, 51, 31));
        itens_l = new QLabel(groupBox_3);
        itens_l->setObjectName(QString::fromUtf8("itens_l"));
        itens_l->setGeometry(QRect(60, 50, 31, 31));
        itens_l->setAlignment(Qt::AlignCenter);
        max_l = new QLabel(groupBox_3);
        max_l->setObjectName(QString::fromUtf8("max_l"));
        max_l->setGeometry(QRect(660, 56, 31, 20));
        max_l->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        label_10 = new QLabel(groupBox_3);
        label_10->setObjectName(QString::fromUtf8("label_10"));
        label_10->setGeometry(QRect(620, 50, 41, 31));
        pushButton = new QPushButton(centralWidget);
        pushButton->setObjectName(QString::fromUtf8("pushButton"));
        pushButton->setGeometry(QRect(20, 440, 99, 27));
        pushButton_2 = new QPushButton(centralWidget);
        pushButton_2->setObjectName(QString::fromUtf8("pushButton_2"));
        pushButton_2->setGeometry(QRect(130, 440, 99, 27));
        pushButton_3 = new QPushButton(centralWidget);
        pushButton_3->setObjectName(QString::fromUtf8("pushButton_3"));
        pushButton_3->setGeometry(QRect(240, 440, 99, 27));
        mainWindow->setCentralWidget(centralWidget);
        groupBox->raise();
        groupBox_2->raise();
        groupBox_3->raise();
        pushButton->raise();
        pushButton_2->raise();
        pushButton_3->raise();
        frame->raise();
        menuBar = new QMenuBar(mainWindow);
        menuBar->setObjectName(QString::fromUtf8("menuBar"));
        menuBar->setGeometry(QRect(0, 0, 740, 25));
        mainWindow->setMenuBar(menuBar);

        retranslateUi(mainWindow);

        QMetaObject::connectSlotsByName(mainWindow);
    } // setupUi

    void retranslateUi(QMainWindow *mainWindow)
    {
        mainWindow->setWindowTitle(QApplication::translate("mainWindow", "movingRobots", 0, QApplication::UnicodeUTF8));
        robot1->setText(QApplication::translate("mainWindow", "1", 0, QApplication::UnicodeUTF8));
        robot3->setText(QApplication::translate("mainWindow", "3", 0, QApplication::UnicodeUTF8));
        robot2->setText(QApplication::translate("mainWindow", "2", 0, QApplication::UnicodeUTF8));
        groupBox->setTitle(QApplication::translate("mainWindow", "Positions", 0, QApplication::UnicodeUTF8));
        rob3_y->setText(QApplication::translate("mainWindow", "0", 0, QApplication::UnicodeUTF8));
        rob3_x->setText(QApplication::translate("mainWindow", "0", 0, QApplication::UnicodeUTF8));
        rob2_y->setText(QApplication::translate("mainWindow", "0", 0, QApplication::UnicodeUTF8));
        label_2->setText(QApplication::translate("mainWindow", "Robot 2 :", 0, QApplication::UnicodeUTF8));
        label->setText(QApplication::translate("mainWindow", "Robot 1 :", 0, QApplication::UnicodeUTF8));
        label_4->setText(QApplication::translate("mainWindow", "X", 0, QApplication::UnicodeUTF8));
        label_5->setText(QApplication::translate("mainWindow", "Y", 0, QApplication::UnicodeUTF8));
        label_3->setText(QApplication::translate("mainWindow", "Robot 3 :", 0, QApplication::UnicodeUTF8));
        rob1_y->setText(QApplication::translate("mainWindow", "0", 0, QApplication::UnicodeUTF8));
        rob1_x->setText(QApplication::translate("mainWindow", "0", 0, QApplication::UnicodeUTF8));
        rob2_x->setText(QApplication::translate("mainWindow", "0", 0, QApplication::UnicodeUTF8));
        groupBox_2->setTitle(QApplication::translate("mainWindow", "Times (ms)", 0, QApplication::UnicodeUTF8));
        label_6->setText(QApplication::translate("mainWindow", "4000", 0, QApplication::UnicodeUTF8));
        label_7->setText(QApplication::translate("mainWindow", "4000", 0, QApplication::UnicodeUTF8));
        label_8->setText(QApplication::translate("mainWindow", "4000", 0, QApplication::UnicodeUTF8));
        checkBox->setText(QString());
        checkBox_2->setText(QString());
        checkBox_3->setText(QString());
        label_11->setText(QApplication::translate("mainWindow", "100", 0, QApplication::UnicodeUTF8));
        checkBox_4->setText(QString());
        label_12->setText(QApplication::translate("mainWindow", "S1", 0, QApplication::UnicodeUTF8));
        label_13->setText(QApplication::translate("mainWindow", "S2", 0, QApplication::UnicodeUTF8));
        label_14->setText(QApplication::translate("mainWindow", "S3", 0, QApplication::UnicodeUTF8));
        label_15->setText(QApplication::translate("mainWindow", "P", 0, QApplication::UnicodeUTF8));
        groupBox_3->setTitle(QApplication::translate("mainWindow", "Buffer", 0, QApplication::UnicodeUTF8));
        label_9->setText(QApplication::translate("mainWindow", "Items:", 0, QApplication::UnicodeUTF8));
        itens_l->setText(QApplication::translate("mainWindow", "0", 0, QApplication::UnicodeUTF8));
        max_l->setText(QApplication::translate("mainWindow", "0", 0, QApplication::UnicodeUTF8));
        label_10->setText(QApplication::translate("mainWindow", "Max:", 0, QApplication::UnicodeUTF8));
        pushButton->setText(QApplication::translate("mainWindow", "Remove", 0, QApplication::UnicodeUTF8));
        pushButton_2->setText(QApplication::translate("mainWindow", "Insere", 0, QApplication::UnicodeUTF8));
        pushButton_3->setText(QApplication::translate("mainWindow", "Mostra", 0, QApplication::UnicodeUTF8));
    } // retranslateUi

};

namespace Ui {
    class mainWindow: public Ui_mainWindow {};
} // namespace Ui

QT_END_NAMESPACE

#endif // UI_MAINWINDOW_H
